name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Проверка кода из репозитория
      - uses: actions/checkout@v4

      # Шаг 2: Запуск markdown линта с выводом отчета в формате JSON
      - name: Run markdown lint
        run: |
          npm install remark-cli remark-preset-lint-consistent vfile-reporter-json
          npx remark . --use remark-preset-lint-consistent --report vfile-reporter-json 2> remark-lint-report.json

      # Шаг 3: Загрузка отчета о линтинге как артефакт
      - uses: actions/upload-artifact@v4
        with:
          name: remark-lint-report
          path: remark-lint-report.json
